sb1

diff --git a/sbo/icecat/icecat.SlackBuild b/sbo/icecat/icecat.SlackBuild
--- a/sbo/icecat/icecat.SlackBuild
+++ b/sbo/icecat/icecat.SlackBuild
@@ -27,9 +27,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM="icecat"
-VERSION=${VERSION:-60.7.0}
-RELEASEVER="$VERSION"
-RELEASEVERMAJ=$(echo $RELEASEVER | cut -f 1 -d .)
+VERSION=${VERSION:-115.5.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -66,49 +64,53 @@ else
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a  $OUTPUT/error-${PRGNAM}.log' ERR
 
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}
-cd $PKG/usr/lib${LIBDIRSUFFIX}
-tar xvf $CWD/${PRGNAM}-$VERSION.en-US.gnulinux-$ARCH.tar.bz2
-mv ${PRGNAM} ${PRGNAM}-$VERSION
+rm -rvf $PKG
+mkdir -pv $TMP $PKG $OUTPUT
+cd $TMP
+rm -rvf $PRGNAM-$VERSION
+mkdir -pv $PRGNAM-$VERSION
+cd $PRGNAM-$VERSION
+rpm2cpio < $CWD/${PRGNAM}-${VERSION}-${BUILD}.rh1.fc40.${ARCH}.rpm | cpio -imdv
 
 chown -R root:root .
+
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
   -o -perm 511 \) -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-mkdir $PKG/usr/bin
-cd $PKG/usr/bin
-ln -s /usr/lib${LIBDIRSUFFIX}/${PRGNAM}-$VERSION/icecat icecat
+cp -ap usr $PKG/
+
+rm -rvf $PKG/usr/lib${LIBDIRSUFFIX}/${PRGNAM}/dictionaries
+rm -rvf $PKG/usr/lib${LIBDIRSUFFIX}/${PRGNAM}/${PRGNAM}
 
 # Only OS-dependent addons should be in the OS software channel, and
 # the rest should be installed by the user, or else the user gets
 # stuck with unremovable addons. This especially affects the
 # adblockers, since some of them are incompatible.
 
-cd $PKG/usr/lib${LIBDIRSUFFIX}/${PRGNAM}-$VERSION/browser
-mv extensions disabled-extensions
-mkdir -p extensions
-mv "disabled-extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi" \
-   extensions/
+cd $PKG/usr/lib${LIBDIRSUFFIX}/${PRGNAM}/browser
+mv -v extensions disabled-extensions
+mkdir -pv extensions
 
 # Desktop integration
-mkdir -p $PKG/usr/share/applications
-cat $CWD/icecat.desktop > $PKG/usr/share/applications/icecat.desktop
+#ions
+#cat $CWD/icecat.desktop > $PKG/usr/share/applications/icecat.desktop
 # Need some default icons in the right place:
-cd $PKG/usr/lib${LIBDIRSUFFIX}/${PRGNAM}-$VERSION/browser/chrome/icons/default/
-for i in 16 32 48; do
-  install -m 0644 -D default${i}.png \
-    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/icecat.png
-done
+#cd $PKG/usr/lib${LIBDIRSUFFIX}/${PRGNAM}-$VERSION/browser/chrome/icons/default/
+#for i in 16 32 48; do
+ # install -m 0644 -D default${i}.png \
+  #  $PKG/usr/share/icons/hicolor/${i}x${i}/apps/icecat.png
+#done
 
 # Stage documentation
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp $CWD/README* $PKG/usr/doc/$PRGNAM-$VERSION/
+mv -v $PKG/usr/share/doc/*  $PKG/usr/doc/$PRGNAM-$VERSION
+mv -v $PKG/usr/share/licenses $PKG/usr/doc/$PRGNAM-$VERSION
+rm -rvf $PKG/usr/share/doc
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
